linters:
  BangFormat:
    enabled: true

  BemDepth:
    enabled: true
    max_elements: 1

  BorderZero:
    enabled: true
    convention: zero

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: false

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: false

  DuplicateProperty:
    enabled: false

  ElsePlacement:
    enabled: true
    style: new_line

  EmptyLineBetweenBlocks:
    enabled: false

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short

  HexNotation:
    enabled: true
    style: lowercase

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space
    width: 4

  LeadingZero:
    enabled: true
    style: exclude_zero

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: false

  NestingDepth:
    enabled: false

  PropertyCount:
    enabled: false

  PropertySortOrder:
    enabled: true
    order:
      - position
      - top
      - right
      - bottom
      - left
      - z-index
      - display
      - float
      - width
      - min-width
      - max-width
      - height
      - min-height
      - max-height
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - border
      - border-width
      - border-style
      - border-color
      - border-radius
      - border-top
      - border-top-width
      - border-top-style
      - border-top-color
      - border-right
      - border-right-width
      - border-right-style
      - border-right-color
      - border-bottom
      - border-bottom-width
      - border-bottom-style
      - border-bottom-color
      - border-left
      - border-left-width
      - border-left-style
      - border-left-color
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-right-radius
      - border-bottom-left-radius
      - background
      - background-color
      - background-image
      - background-repeat
      - background-attachment
      - background-position
      - background-size
      - box-shadow
      - font-family
      - font-size
      - font-style
      - font-smoothing
      - font-weight
      - line-height
      - color
      - letter-spacing
      - word-spacing
      - text-align
      - text-decoration
      - text-indent
      - text-shadow
      - text-transform
      - white-space
      - word-wrap
      - word-break
      - content
      - opacity
      - filter
      - vertical-align
      - list-style
      - list-style-type
      - list-style-position
      - list-style-image
      - cursor
      - pointer-events
      - clear
      - overflow
      - overflow-x
      - overflow-y
      - transform
      - transition
      - transition-delay
      - transition-duration
      - transition-property
      - transition-timing-function
      - table-layout
      - box-sizing
      - visibility
      - clip
      - table-layout
      - animation
      - appearance
      - zoom
    ignore_unspecified: false

  PropertySpelling:
    enabled: true

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

    SpaceAroundOperator:
    enabled: true
    style: one_space

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false
    properties:
      - color
      - font

  VendorPrefixes:
    enabled: true
    identifier_list: bourbon

  ZeroUnit:
    enabled: true
